### ISSUE TITLE
Outdated README with glslify

### ISSUE THREAD

**Issue by TatumCreative** [stackgl/gl-shader#10]
I'm having trouble parsing some of what's in the readme, mainly with how this module was much tighter coupled to the older version of glslify.

> var shader = createShader(vertexSource, fragmentSource[, uniforms, attributes])
> ...
> The format of uniforms and attributes is consistent with glslify's output

I'm not sure what this format looks like and what exactly these are supposed to do when you feed them in.

> var shader = createShader(gl, glslifyResult)

Also this says to take the glslify result, which is no longer relevant. Or if that formatting is relevant, it's not clear how to use it with how glslify has changed.

**Comment by mattdesl** [comment]
I've updated the readme and removed references to glslify. Hopefully that clears things up, let me know if there's anything else!

**Comment by TatumCreative** [comment]
Perfect! That's a lot less magical now.
