### ISSUE TITLE
Missing argument check

### ISSUE THREAD

**Issue by abiro** [stackgl/gl-shader#8]
Hi,

The argument check isn't executed on the following line:

https://github.com/stackgl/gl-shader/blob/master/lib/create-attributes.js#L133

I would fix it, but I don't know where the `result` variable comes from a few lines below:

https://github.com/stackgl/gl-shader/blob/master/lib/create-attributes.js#L139

Best regards,
Agost

**Comment by mikolalysenko** [comment]
Yeah, that is a bug.  I can fix it tonight.

**Comment by abiro** [comment]
Thanks!

Mikola Lysenko <notifications@github.com> schrieb am Di., 10. Nov. 2015
18:46:
